name = "code_reviewer"
description = "Automatic Code Reviewer of Ada Code"
version = "0.0.0"

authors = ["Pierre van de Laar"]
maintainers = ["Pierre van de Laar <pierre.van.de.laar@gmail.com>"]
maintainers-logins = ["pjljvandelaar"]

executables = ["code_reviewer"]

[[depends-on]]
libadalang = "^22.0.0"
rejuvenation = "*"
rewriters = "*"
patchers = "*"

[[pins]]
rewriters = { path = ".." }
patchers = { path = "../../patchers" }             # to be decided : separate package?
rejuvenation = { path = "../../rejuvenation" }     # remove before release

